### ISSUE TITLE
Change requested for AppCenter: Don’t use system icon

### ISSUE THREAD

**Issue by cassidyjames** [manexim/typewriter#2]
Thanks for submitting your app! However, it looks like it uses a copy of the system `accessories-text-editor` icon; your app needs to have its own unique icon. It should also include all required sizes as listed in the [Publishing Requirements](https://github.com/elementary/houston/wiki/Before-You-Publish#icons).

For clarity, we have amended the icon requirements to include:

>Icons should be unique to your app; do not use copies of system icons—though a substantial deviation based on a system icon is acceptable. Icons should also not be confusingly similar to other AppCenter app icons.

**Comment by meisenzahl** [comment]
@cassidyjames thanks for the feedback!

I hope the new icon meets the requirements. The icon is based on the system icons `accessories-text-editor` and `input-keyboard`.

![com github manexim typewriter svg](https://user-images.githubusercontent.com/10796736/73610617-9d72fd00-45d9-11ea-9f54-f77be536fa70.png)

**Comment by NathanBnm** [comment]
@meisenzahl you still have to generate this icon at these defferents sizes: 16, 24, 32, 48, 64 and 128 pixels

**Comment by meisenzahl** [comment]
Thanks for the feedback!

I adjusted the color of the icon and included all required icon sizes.

![icons](https://user-images.githubusercontent.com/10796736/74083964-0a6b1480-4a6a-11ea-911a-df307f1ab4d6.png)
