### ISSUE TITLE
auto save file location for sync?

### ISSUE THREAD

**Issue by mashtonian** [manexim/typewriter#26]
I love the simplicity, speed and ease of use of this app, it is miles better for quick jotting needs than any other app I have found.

One thing I would like to know, and can't figure out due to flatpak, is where the autosaved text is stored.

I would like to be able to periodically sync the saved text to an online storage location for backup and so that I can refer to it from a mobile device.

Can you point me in the right direction?

**Comment by meisenzahl** [comment]
@mashtonian glad you like Typewriter.

The text will be saved in your home directory in `.var/app/com.github.manexim.typewriter/data/com.github.manexim.typewriter/autosave.md`.
